---
title: "R - Assignment"
author: "Kohisha Aruganti"
date: "March 21 2022"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# Once installed, load the library.
library(ezids)
```

```{r init, include=F}
project1 = data.frame(read.csv("heart_2020_cleaned.csv"))
project <- subset(project1,select = c(HeartDisease, Smoking, AlcoholDrinking, Diabetic))
str(project)
```


```{r}
library(tidyr)

sum(is.na(total$AlcoholDrinking))
sum(is.na(project$Smoking))
sum(is.na(project$HeartDisease))
sum(is.na(project$Diabetic))
#project[is.na(project) | project=="Inf"] = NA
#project$HeartDisease<- subset(project, is.na(HeartDisease)==FALSE) # eliminating the missing values
#summary(project$HeartDisease)
#project[is.na(project) | project=="Inf"] = NA
#project$Diabetic<- subset(project, is.na(Diabetic)==FALSE) # eliminating the missing values
#summary(project$Diabetic)

project %>% drop_na(Diabetic)
project %>% drop_na(Smoking)
project %>% drop_na(AlcoholDrinking)
#is.na(project)
```
Checking if there are any missing values in the dataset project.
we can see that there are no missing values for smoking and alcoholdrinking.

```{r}
barplot(table(project1$Smoking, project1$HeartDisease), legend= rownames(table(project1$Smoking, project1$HeartDisease)), col =(c("orange", "blue")), xlab="heartdisease", ylab="smoking",main = "Barplot for Heartdisease and Smoking")
```


```{r}
barplot(table(project1$AlcoholDrinking, project1$HeartDisease), legend= rownames(table(project1$AlcoholDrinking, project1$HeartDisease)), col =(c("red", "darkblue")), xlab="Heartdisease", ylab="Alcoholdrinking", main = "Barplot for Heartdisease and Alcoholdrinking")
```

```{r}
barplot(table(project1$HeartDisease, project1$Diabetic), legend= rownames(table(project1$HeartDisease, project1$Diabetic)), col =(c("green", "brown")),xlab="Diabetic",ylab="HeartDisease", main = "Barplot for Heartdisease and Diabetic")
```

```{r}
library(plyr)
project$Diabetic<- replace (project$Diabetic, project$Diabetic== "No, borderline diabetes" , "Yes")
project$Diabetic[project$Diabetic== "Yes (during pregnancy)"] <- "No"  

#project$HeartDisease<-ifelse(project$HeartDisease=="Yes",1,0)
#project$Smoking<-ifelse(project$Smoking=="Yes",1,0)
#project$AlcoholDrinking<-ifelse(project$AlcoholDrinking=="Yes",1,0)
#project$Diabetic<-ifelse(project$Diabetic=="Yes",1,0)


project$HeartDisease <- revalue(project$HeartDisease, c("Yes"=1))
project$HeartDisease<- revalue(project$HeartDisease, c("No"=0))
project$AlcoholDrinking <- revalue(project$AlcoholDrinking, c("Yes"=1))
project$AlcoholDrinking <- revalue(project$AlcoholDrinking, c("No"=0))
project$Smoking <- revalue(project$Smoking, c("Yes"=1))
project$Smoking <- revalue(project$Smoking, c("No"=0))
project$Diabetic  <- revalue(project$Diabetic , c("Yes"=1))
project$Diabetic  <- revalue(project$Diabetic , c("No"=0))
project$Diabetic  <- revalue(project$Diabetic , c("No,borderline diabetes"="No"))
project$Diabetic  <- revalue(project$Diabetic , c("Yes (during pregnancy)"="Yes"))


project

```

```{r}
project$HeartDisease <- as.numeric(project$HeartDisease)
project$Smoking <- as.numeric(project$Smoking)
project$AlcoholDrinking <- as.numeric(project$AlcoholDrinking)
project$Diabetic <- as.numeric(project$Diabetic)
str(project)
```


```{r}

lm1 <- lm(HeartDisease ~ AlcoholDrinking + Smoking + AlcoholDrinking:Smoking, data = project)
xkabledply(lm1, title = paste("Model :", format(formula(lm1)) ) )
xkablevif(lm1)
summary(lm1)
```

```{r}
plot(lm1)
```

```{r}
lm2 <- lm(HeartDisease ~ Smoking + AlcoholDrinking + Diabetic + Smoking : Diabetic + Diabetic: AlcoholDrinking,data = total)
xkabledply(lm2, title = paste("Model :", format(formula(lm2)) ) )
xkablevif(lm2)
summary(lm2)

```


```{r}
lm3 <- lm(Diabetic ~ Smoking + AlcoholDrinking + Smoking : AlcoholDrinking,data = total)
xkabledply(lm3, title = paste("Model :", format(formula(lm3)) ) )
xkablevif(lm3)
summary(lm3)
```


```{r}
library(dyn)
anovaRes = aov(HeartDisease ~ AlcoholDrinking, data=total)
xkabledply(anovaRes, title = "ANOVA result summary")

anovaRes1 = aov(HeartDisease ~ Smoking, data=total)
xkabledply(anovaRes1, title = "ANOVA result summary")

```

```{r}
percent <- xtabs(~total$AlcoholDrinking+ total$Smoking + total$HeartDisease)
ftable(prop.table(percent))* 100

```

# Correlation coefficient 

```{r}
cor_ad_smoke <- cor(total$AlcoholDrinking, total$Smoking)
summary(cor_ad_smoke)
cor_as_hd <- cor(total$AlcoholDrinking, total$HeartDisease)
summary(cor_as_hd)
cor_hd_smoke <- cor(total$HeartDisease, total$Smoking)
summary(cor_hd_smoke)


```

```{r}
contable  <- table(total$HeartDisease, total$Smoking)
summary(contable ) 
prop <-prop.table(contable)
percent <- round(prop*100, 2)
xkabledply(percent, title="Contingency Table for heart Disease and Smoking in Percentage")
```

```{r}
contable2 <- table(total$HeartDisease, total$AlcoholDrinking)
summary(contable2) 
prop <-prop.table(contable2)
percent <- round(prop*100, 2)
xkabledply(percent, title="Contingency Table for heart Disease and Smoking in Percentage")
```

```{r chisq}

chitest1 = chisq.test(contable)
chitest1
chitest2 = chisq.test(contable2)
chitest2
```


```{r}
heartsub <- data.frame(project)
heartsub <- heartsub[, c("HeartDisease","Diabetic","Smoking", "AlcoholDrinking")]
head(heartsub)

newdata1<- subset(heartsub, HeartDisease==1)
newdata1_1<-head(newdata1,27373)
nrow(newdata1_1)
newdata0<- subset(heartsub, HeartDisease==0)
newdata0_1<-head(newdata0,27373)
nrow(newdata0_1)
total <- rbind(newdata1_1, newdata0_1)
nrow(total)
summary(total)
```


```{r}
set.seed(123)
train_rows <- sample(c(TRUE, FALSE), nrow(heartsub), replace=TRUE, prob=c(0.8,0.2))
train <- heartsub[train_rows, ]
test <- heartsub[-train_rows, ]
```

```{r}

model_lr <- glm(HeartDisease ~ Smoking + AlcoholDrinking , data = train , family = "binomial")
summary(model_lr)
xkabledply(model_lr, title = paste("Logistic Regression :", format(formula(model_lr))))
```

```{r}
anova(model_lr, test="Chisq")
```

```{r}
fitted.results <- predict(model_lr,newdata = test, type='response')
fitted.results <- ifelse(fitted.results > 0.5,1,0)
misClasificError <- mean(fitted.results != test$HeartDisease)
print(paste('Accuracy',1-misClasificError))

```

```{r}
expcoeff = exp(coef(model_lr))
xkabledply( as.table(expcoeff), title = "Exponential of coefficients in Logit Reg" )
```

### Using Confidence Intervals

```{r, results='hold'}


xkabledply(confint(model_lr), title = "CIs using profiled log-likelihood" )
xkabledply(confint.default(model_lr), title = "CIs using standard errors" )
```

### Model evaluation
#### Confusion matrix 

```{r confusionMatrix, results='markup'}
loadPkg("regclass")
xkabledply( confusion_matrix(model_lr), title = "Confusion matrix from Logit Model" )

```
#### Receiver-Operator-Characteristic (ROC) curve and Area-Under-Curve (AUC)

```{r}
loadPkg("pROC") 

model2 = predict(model_lr, type = "response" )
#h <- roc(HeartDisease ~ model_lr, data=total)
auc(h) 
plot(h)
library(ROCR)
p <- predict(model_lr, newdata=test, type="response")
pr <- prediction(p, test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc


```

```{r}
#install.packages("caret")
#install.packages("optimal.cutpoints()")
#install.packages("InformationValue")
#library(caret)
#use model to predict probability of default
train_prediction <- predict( model_lr, newdata = train, type = "response" )
test_prediction  <- predict( model_lr, newdata = test , type = "response" )
#find optimal cutoff probability to use to maximize accuracy
#optimal <- optimalCutoff(test$total, predicted)[1]
#optimalCutoff(actuals, predictedScores, optimiseFor = "misclasserror", returnDiagnostics = FALSE)

#confusionMatrix(test$total, as.factor(train_prediction))
```


```{r}

model_lr2 <- glm(HeartDisease ~ Smoking + AlcoholDrinking  + Diabetic + Smoking:Diabetic , data = total , family = "binomial")
summary(model_lr2)
xkabledply(model_lr2, title = paste("Logistic Regression :", format(formula(model_lr2))))
```
```{r}
fitted.results2 <- predict(model_lr2,newdata = test, type='response')
fitted.results2 <- ifelse(fitted.results2 > 0.5,1,0)
misClasificError2 <- mean(fitted.results2 != test$HeartDisease)
print(paste('Accuracy',1-misClasificError2))

```

```{r, results='hold'}


xkabledply(confint(model_lr2), title = "CIs using profiled log-likelihood" )
xkabledply(confint.default(model_lr2), title = "CIs using standard errors" )
```
### Model evaluation
#### Confusion matrix 

```{r confusionMatrix, results='markup'}
loadPkg("regclass")
xkabledply( confusion_matrix(model_lr2), title = "Confusion matrix from Logit Model" )
```


```{r}

library("corrplot")

y <- cor(total)
co_matrix<-cor(total)
co_matrix
corrplot(y,method="number",title = "Correlation of numberical variables",mar = c(1,0,2,0))

```

```{r}

train_prediction11<- predict( model_lr2, newdata = train, type = "response" )
test_prediction1   <- predict( model_lr2, newdata = test , type = "response" )
```

```{r}
loadPkg("pROC") 


library(ROCR)
p1 <- predict(model_lr2, newdata=test, type="response")
pr1 <- prediction(p1, test$HeartDisease)
prf1 <- performance(pr2, measure = "tpr", x.measure = "fpr")
plot(prf1)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc


```


